\# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.1

env:
  - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=9.1"
  - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=8.4"
  - DESTINATION="platform=iOS Simulator,name=iPad Air,OS=9.1"
  - DESTINATION="platform=iOS Simulator,name=iPad Air,OS=8.4"

script:
- set -o pipefail && xcodebuild test -destination=$DESTINATION -workspace Example/Alamofire-Decoded.xcworkspace -scheme Alamofire-Decoded-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
